### ISSUE TITLE
"https://cors-anywhere.herokuapp.com/" is down

### ISSUE THREAD

**Issue by liamzhang40** [Rob--W/cors-anywhere#142]
![screen shot 2018-10-29 at 11 43 40 pm](https://user-images.githubusercontent.com/33468366/47694570-81153300-dbd4-11e8-94eb-19a36177513b.png)

I am using this for Yelp API

Time to response: ~ 70 - 90 ms
HTTP status code in response: 503
HTTP response body: 
![screen shot 2018-10-29 at 11 48 10 pm](https://user-images.githubusercontent.com/33468366/47694707-26c8a200-dbd5-11e8-876a-e5e210ee75e8.png)

and this is intermittently (second time it happened to me)

hopefully this is helpful for debugging

**Comment by egfx** [comment]
This happens all the time. But this time it's different. The URL is working https://cors-anywhere.herokuapp.com/ but the actual requests are corrupted.

**Comment by Rob--W** [comment]
I started capturing the access logs almost 10 hours ago. Do you have a specific example of a failure?

The absence of CORS headers suggests that there may be an operational (server) issue.

**Comment by egfx** [comment]
Did you start blocking requests from any particular sites? It seems this is a globally scoped problem.

**Comment by Rob--W** [comment]
The latest status of blocks is in https://github.com/Rob--W/cors-anywhere/issues/129#issuecomment-433005558 . When blocked, the response is immediate and the status code is either 403 or 429.

503 after a timeout sounds like a resource problem (i.e. too many people trying to use the public demo). But I can only confirm whether that is the case if you provide a concrete example of a failure. I'm not going to capture the log forever, so please share an example if you can.

**Comment by egfx** [comment]
It's coming back as a 503 error. I don't think my particular payload is being blocked. I'm not sending more then 1 or 2 requests at a time.

**Comment by Rob--W** [comment]
Please provide the exact URL and time. Otherwise I cannot investigate it.

**Comment by egfx** [comment]
Any and all image URL's will result in the same 503. For example this picture @ 1:13pm PST https://cors-anywhere.herokuapp.com/https://i.imgur.com/4U89t5z.jpg

**Comment by Rob--W** [comment]
Thanks, that helped! Apparently this is not an operational issue, but an application error (which probably happened when Node.js was bumped to the latest version in the latest update):

```
2018-10-30T13:33:33.662806+00:00 app[web.1]: _http_outgoing.js:464
2018-10-30T13:33:33.662810+00:00 app[web.1]: throw err;
2018-10-30T13:33:33.662811+00:00 app[web.1]: ^
2018-10-30T13:33:33.662813+00:00 app[web.1]: 
2018-10-30T13:33:33.662815+00:00 app[web.1]: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["user-agent"]
2018-10-30T13:33:33.662817+00:00 app[web.1]: at ClientRequest.setHeader (_http_outgoing.js:473:3)
2018-10-30T13:33:33.662818+00:00 app[web.1]: at new ClientRequest (_http_client.js:193:14)
2018-10-30T13:33:33.662820+00:00 app[web.1]: at Object.request (http.js:41:10)
2018-10-30T13:33:33.662822+00:00 app[web.1]: at Array.stream (/app/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:108:74)
2018-10-30T13:33:33.662823+00:00 app[web.1]: at ProxyServer.<anonymous> (/app/node_modules/http-proxy/lib/http-proxy/index.js:80:21)
2018-10-30T13:33:33.662825+00:00 app[web.1]: at proxyRequest (/app/lib/cors-anywhere.js:134:9)
2018-10-30T13:33:33.662827+00:00 app[web.1]: at Server.<anonymous> (/app/lib/cors-anywhere.js:396:5)
2018-10-30T13:33:33.662829+00:00 app[web.1]: at Server.emit (events.js:182:13)
2018-10-30T13:33:33.662830+00:00 app[web.1]: at parserOnIncoming (_http_server.js:652:12)
2018-10-30T13:33:33.662832+00:00 app[web.1]: at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

I'll work on a fix.

**Comment by egfx** [comment]
it was working for 24 hours and working prior to the fix. Now it's not working anymore :-1:

**Comment by Rob--W** [comment]
Yesterday I pushed the update to this repository to run automated tests. Since all tests have passed, I have now published the changes to the public CORS Anywhere demo, which solves the problem.
