### ISSUE TITLE
error log - after update SSL certificate

### ISSUE THREAD

**Issue by hoogw** [Rob--W/cors-anywhere#219]
I am on centOS server, 

I just installed a new SSL certificate on centOS server.

I have 2 node.js app runing, and the other node.js with newly copied public cert/private key without problem. 

But only this cors-anywhere run to error.
error log is here:  

 Do you see any hint?

         `      Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:158:17)
    at Server.setSecureContext (_tls_wrap.js:1080:27)
    at Server (_tls_wrap.js:960:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.createServer (/home/hoogw2000/node/cors-anywhere/lib/cors-anywhere.js:405:31)
    at Object.<anonymous> (/home/hoogw2000/node/cors-anywhere/server.js:88:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loa`

**Comment by hoogw** [comment]
server.js is here
                      `
// must install load dotenv to be able to use .env file
require('dotenv').config();

var fs = require('fs');

// Listen on a specific host via the HOST environment variable
var host = process.env.HOST || '0.0.0.0';
// Listen on a specific port via the PORT environment variable
var port = process.env.PORT || 8080;  // for http



var port_https = process.env.PORT_https || 8080; // for https




// Grab the blacklist from the command-line so that we can update the blacklist without deploying
// again. CORS Anywhere is open by design, and this blacklist is not used, except for countering
// immediate abuse (e.g. denial of service). If you want to block all origins except for some,
// use originWhitelist instead.
var originBlacklist = parseEnvList(process.env.CORSANYWHERE_BLACKLIST);
var originWhitelist = parseEnvList(process.env.CORSANYWHERE_WHITELIST);
function parseEnvList(env) {
  if (!env) {
    return [];
  }
  return env.split(',');
}



console.log('port, http, https : ', port, port_https)
console.log('originWhitelist', originWhitelist)






// Set up rate-limiting to avoid abuse of the public CORS Anywhere server.
var checkRateLimit = require('./lib/rate-limit')(process.env.CORSANYWHERE_RATELIMIT);



// ************** http ***************************


        var cors_proxy = require('./lib/cors-anywhere');


        cors_proxy.createServer({

          originBlacklist: originBlacklist,
          originWhitelist: originWhitelist,
          requireHeader: ['origin', 'x-requested-with'],
          checkRateLimit: checkRateLimit,
          removeHeaders: [
            'cookie',
            'cookie2',
            // Strip Heroku-specific headers
            'x-heroku-queue-wait-time',
            'x-heroku-queue-depth',
            'x-heroku-dynos-in-use',
            'x-request-start',
          ],
          redirectSameOrigin: true,
          httpProxyOptions: {
            // Do not add X-Forwarded-For, etc. headers, because Heroku already adds it.
            xfwd: false,
          },
        }).listen(port, host, function() {
          console.log('Running CORS Anywhere http :  ' + host + ':' + port);
        });


// ************** end *************  http ***************************





// ************** https ***************************
        var cors_proxy_https = require('./lib/cors-anywhere');


        cors_proxy_https.createServer({

        // add https support  
        //https://github.com/Rob--W/cors-anywhere/issues/74



          httpsOptions: {
            key: fs.readFileSync(__dirname + '/private.key', 'utf8'),
            cert: fs.readFileSync(__dirname + '/public.cert', 'utf8')
          },


// ********** end **** https ***************************

  originBlacklist: originBlacklist,
  originWhitelist: originWhitelist,
  requireHeader: ['origin', 'x-requested-with'],
  checkRateLimit: checkRateLimit,
  removeHeaders: [
    'cookie',
    'cookie2',
    // Strip Heroku-specific headers
    'x-heroku-queue-wait-time',
    'x-heroku-queue-depth',
    'x-heroku-dynos-in-use',
    'x-request-start',
  ],
  redirectSameOrigin: true,
  httpProxyOptions: {
    // Do not add X-Forwarded-For, etc. headers, because Heroku already adds it.
    xfwd: false,
  },
}).listen(port_https, host, function() {
  console.log('Running CORS Anywhere https ' + host + ':' + port_https);
});
`

**Comment by hoogw** [comment]
server-out.log is here:


                          `port 7000
originWhitelist [ 'https://transparentgov.net',
  'http://transparentgov.net',
  'http://transparentgov.net:3000',
  'https://transparentgov.net:3200',
  'https://transparentgov.net:10',
  'http://transparentgov.net:10',
  'http://localhost:10',
  'http://localhost:3000',
  'https://localhost:3200' ]
Running CORS Anywhere on 0.0.0.0:7000
port, http, https :  7000 7200
originWhitelist [ 'https://transparentgov.net',
  'http://transparentgov.net',
  'http://transparentgov.net:3000',
  'https://transparentgov.net:3200',
  'https://transparentgov.net:10',
  'http://transparentgov.net:10',
  'http://localhost:10',
  'http://localhost:3000',
  'https://localhost:3200' ]
Running CORS Anywhere http :  0.0.0.0:7000
Running CORS Anywhere https 0.0.0.0:7200
port, http, https :  7000 7200
originWhitelist [ 'https://transparentgov.net',
  'http://transparentgov.net',
  'http://transparentgov.net:3000',
  'https://transparentgov.net:3200',
  'https://transparentgov.net:10',
  'http://transparentgov.net:10',
  'http://localhost:10',
  'http://localhost:3000',
  'https://localhost:3200' ]
Running CORS Anywhere http :  0.0.0.0:7000
Running CORS Anywhere https 0.0.0.0:7200
port, http, https :  7000 7200
originWhitelist [ 'https://transparentgov.net',
  'http://transparentgov.net',
  'http://transparentgov.net:3000',
  'https://transparentgov.net:3200',
  'https://transparentgov.net:10',
  'http://transparentgov.net:10',
  'http://localhost:10',
  'http://localhost:3000',
  'https://localhost:3200' ]`

**Comment by Rob--W** [comment]
The key and certificate must both be in the PEM format. Is that the case/

**Comment by hoogw** [comment]
Never mind, it was because of centOS directory user access folder denied. cause the above error.

centOS have one root admin account and a apache web public_html account. 

If you put this app under apache , folder public_html, you must use that special apache web account to run npm start server.js

If you put this app outside of 'public_html' folder, anywhere, you must NOT use that account, 
instead, you must use admin root account to run npm start server.js

If you failed to follow above rules, you will get this error, 
even you don't get this error, your SSL will failed to work, the whole app failed to work.

**Comment by hoogw** [comment]
I have fix the error, approve that SSL is working as:

[https://transparentgov.net:7200](https://transparentgov.net:7200)

To Add SSL to this app, see above my code.
