### ISSUE TITLE
Responses with invalid redirects may crash the server

### ISSUE THREAD

**Issue by Rob--W** [Rob--W/cors-anywhere#234]
There have been reports of the server being unreachable (e.g. #233). I started to watch the log stream, and found the following runtime error:

```
/app/lib/cors-anywhere.js:82
 req.url = location.path;
 ^
 
 TypeError: Cannot read property 'path' of null
 at proxyRequest (/app/lib/cors-anywhere.js:82:22)
 at onProxyResponse (/app/lib/cors-anywhere.js:202:11)
 at ClientRequest.<anonymous> (/app/lib/cors-anywhere.js:103:17)
 at ClientRequest.emit (events.js:315:20)
 at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:632:27)
 at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
 at HTTPParser.execute (<anonymous>)
 at Socket.socketOnData (_http_client.js:501:22)
 at Socket.emit (events.js:315:20)
 at addChunk (_stream_readable.js:300:12)
```

This could happen if the server receives a redirect to an invalid URL. I recently made the URL validation a bit more strict, which probably increased the likelihood of triggering this bug.

**Comment by egfx** [comment]
good catch!
