### ISSUE TITLE
Debian buster: Error:SSL routines:SSL_CTX_use_certificate:ee key too small

### ISSUE THREAD

**Issue by MaxPeal** [Rob--W/cors-anywhere#276]
npm run test fail on Debian buster or newer, as 
With the introduction of [openssl version 1.1.1]((https://wiki.debian.org/ContinuousIntegration/TriagingTips/openssl-1.1.1)) in Debian, the defaults are set to more secure values by default:
...
This means that RSA and DHE keys need to be at least 2048 bit long. SHA-1 is no longer supported for signatures in certificates and you need at least SHA-256. Note that CAs have stopped issuing certificates that didn't meet those requirements in January 2015, and since January 2017 all valid CA certificates should meet those requirements. However there are certificates generated by private CAs or that are in a test suite that do not meet those requirements. 
...

so the test will fail:
```
npm run test
...
100 passing (5s)
2 failing

    server on https "before all" hook:
    Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
    at Object.createSecureContext (_tls_common.js:129:17)
    at Server.setSecureContext (_tls_wrap.js:1323:27)
    at Server (_tls_wrap.js:1181:8)
    at new Server (https.js:66:14)
    at Object.createServer (https.js:90:10)
    at createServer (lib/cors-anywhere.js:417:31)
    at Context. (test/test.js:500:21)
    at processImmediate (internal/timers.js:461:21)

    server on https "after all" hook:
    TypeError: Cannot read property 'close' of null
    at stopServer (test/test.js:35:17)
    at Context. (test/test.js:517:5)
    at processImmediate (internal/timers.js:461:21)

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cors-anywhere@0.4.3 test: mocha ./test/test*.js --reporter spec
npm ERR! Exit status 2
npm ERR!
...
```

**Comment by MaxPeal** [comment]
see the CI test #271 #273
