### ISSUE TITLE
Error: Cannot find module 'http-proxy'

### ISSUE THREAD

**Issue by darkrole** [Rob--W/cors-anywhere#49]
when i try to run server.js on node.js im getting this error: 
Error: Cannot find module 'http-proxy'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\cors-anywhere\lib\cors-anywhere.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! This is most likely a problem with the cors-anywhere package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cors-anywhere
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls cors-anywhere
npm ERR! There is likely additional logging output above.

**Comment by darkrole** [comment]
fixed with: node install http-proxy
thanks!

**Comment by Rob--W** [comment]
Use `npm install` to make sure that all dependencies (and the correct
version) in package.json are installed.

**Comment by uhlenkott** [comment]
We ran the npm install http-proxy without any luck. Is there another route we can try?

**Comment by kirtish10** [comment]
bata do bhaii ko..project nai challaa

**Comment by ZuhaibSohail163** [comment]
bata do bhaii ko..project nai challaa
