### ISSUE TITLE
RangeError: Invalid status code: 0

### ISSUE THREAD

**Issue by Rob--W** [Rob--W/cors-anywhere#95]
The public demo server has been failing intermittently.

When I watch the logs ( `./node_modules/.bin/heroku logs --app cors-anywhere` ), I see the following error at some point, after which the server is unavailable for a while (before it is automatically restarted).

```
2017-11-08T17:40:51.959869+00:00 app[web.1]: _http_server.js:192
2017-11-08T17:40:51.959871+00:00 app[web.1]:     throw new RangeError(`Invalid status code: ${statusCode}`);
2017-11-08T17:40:51.900841+00:00 heroku[router]: at=info method=GET path="/[HTTP URL REDACTED]" host=cors-anywhere.herokuapp.com request_id=a24e02a6-7a22-4cc6-8ea4-057afd0ab5bc fwd="[IP ADDRESS REDACTED]" dyno=web.1 connect=0ms service=242ms status=429 bytes=467 protocol=https
2017-11-08T17:40:51.959872+00:00 app[web.1]:     ^
2017-11-08T17:40:51.959873+00:00 app[web.1]: 
2017-11-08T17:40:51.959874+00:00 app[web.1]: RangeError: Invalid status code: 0
2017-11-08T17:40:51.959875+00:00 app[web.1]:     at ServerResponse.writeHead (_http_server.js:192:11)
2017-11-08T17:40:51.959876+00:00 app[web.1]:     at Array.writeStatusCode (/app/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:99:9)
2017-11-08T17:40:51.959877+00:00 app[web.1]:     at ClientRequest.<anonymous> (/app/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:149:20)
2017-11-08T17:40:51.959877+00:00 app[web.1]:     at emitOne (events.js:90:13)
2017-11-08T17:40:51.959878+00:00 app[web.1]:     at ClientRequest.emit (events.js:182:7)
2017-11-08T17:40:51.959879+00:00 app[web.1]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:469:21)
2017-11-08T17:40:51.959880+00:00 app[web.1]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
2017-11-08T17:40:51.959881+00:00 app[web.1]:     at TLSSocket.socketOnData (_http_client.js:359:20)
2017-11-08T17:40:51.959882+00:00 app[web.1]:     at emitOne (events.js:90:13)
2017-11-08T17:40:51.959886+00:00 app[web.1]:     at TLSSocket.emit (events.js:182:7)
```

**Comment by Rob--W** [comment]
This particular crash has been observed before in the library that I use: https://github.com/nodejitsu/node-http-proxy/issues/1080
